version: "3"

networks:
  mmp-dev-net:

services:

  # The web service
  mmp:
    hostname: mmp
    container_name: mmp
    image: mmp_dev:latest
    environment:
      - FUTURE_ENV=future_env
    networks:
      - mmp-dev-net
    expose:
      - 80
    ports:
      - 40000:80
    volumes:
      ## Edit this to the local location of your mmp project
      - ~/src/matrixmath-perl/lib:/var/www/mmp/lib
      - ~/src/matrixmath-perl/public:/var/www/mmp/public
      - ~/src/matrixmath-perl/script:/var/www/mmp/script
      - ~/src/matrixmath-perl/t:/var/www/mmp/t
      - ~/src/matrixmath-perl/templates:/var/www/mmp/templates

    restart: always

  # TODO don't expose mmp container, setup nginx proxy container
  # nginx:

